# Generated by Django 2.1.5 on 2019-02-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190212_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_pub',
            new_name='pub_date',
        ),
    ]
